### ISSUE TITLE
webos system images install failed on Rosy(redmi 5)

### ISSUE THREAD

**Issue by shh632058099** [webOS-ports/meta-webos-ports#389]
I install webos system images on my rosy device, when taring webos-rootfs.tar.gz to  /data/luneos_tmp_extract, the phone will reboot unexpectly,and install failed.
test case:
1.luneos-dev-package-rosy-20181120212426-stable-053-2.zip  install succeed
2.luneos-dev-package-rosy--testing-0-54.zip and later version will install failed

**Comment by Herrie82** [comment]
@shh632058099 We've seen this behavior as well. We're looking into it. @Tofee has a rosy as well and he'll find a solution eventually I'm sure ;)

**Comment by shh632058099** [comment]
@Herrie82 And other devices have the same problem?  
thanks

**Comment by Herrie82** [comment]
Tissot seems to work fine, just like Hammerhead. We added these fixes because we got out of memory in some cases previously: https://github.com/webOS-ports/android-update-package/commit/a15dbbe778c6691d8f91767557dc685134e1ed33, https://github.com/webOS-ports/android-update-package/commit/51bb0acedf1640827f51d20fb88cd215b83a567e and https://github.com/webOS-ports/android-update-package/commit/481644a737cf43c5829e39d3fd888115d4393426

**Comment by shh632058099** [comment]
@Herrie82 Is there a right way to build latest stable version? I follow the 'Build for Rosy' help content, and lots of fetching error occur.

**Comment by Herrie82** [comment]
In which step? My builds usually work fine. I haven't tried Rosy, but Tissot worked fine earlier last week.

**Comment by shh632058099** [comment]
The building step, lots of bb recipes  point to a branch which is not exist now,and fetching code failed

**Comment by Herrie82** [comment]
Are you sure you exported and cloned the testing branch? That's what we're using and it builds fine. I.e. these steps:

$ export ENV_NAME=testing
$ wget https://raw.github.com/webOS-ports/webos-ports-setup/$ENV_NAME/Makefile
$ make setup-webos-ports

We built a new image yesterday for Rosy, logs are at: http://jenkins.nas-admin.org/job/LuneOS/job/luneos-testing_rosy/63/consoleFull

It could be some URLs are blocked from your location somehow?

**Comment by shh632058099** [comment]
We build stable branch like these steps:
$ export ENV_NAME=stable
$ wget https://raw.github.com/webOS-ports/webos-ports-setup/$ENV_NAME/Makefile
$ make setup-webos-ports

The testing branch is built sucessfully, I just want to have a check whether the lastet stable branch is ok on my rosy device.

**Comment by Herrie82** [comment]
For stable you can just download the image from our build server. There are no changes to it since then. We only do new stable image when we push out a release. Everything else is "testing". http://build.webos-ports.org/releases/doppio/images/rosy/

**Comment by shh632058099** [comment]
@Herrie82 Hi, I ported webos to my new device. when I boot system, android container starts failed, and nothing logs is displayed, is there a easy way to debug that?

**Comment by Herrie82** [comment]
@shh632058099 Which device is it? Can you reboot to recovery and pull /sys/fs/pstore/console-ramoops ? That should give some clues normally.

**Comment by Tofee** [comment]
Also, check if adb works, that would allow you to look for errors in the
journal.
But yes, if nothing boots, then the pstore log is a good idea.

**Comment by shh632058099** [comment]
@Herrie82 On, thanks, I will hava a try. My device is an embedded device which only contains fastboot.

**Comment by Herrie82** [comment]
Which device are you working on, or it's not a generally available device?

**Comment by Tofee** [comment]
Device flashing issue should be more stable when https://github.com/webOS-ports/meta-webos-ports/pull/402 is merged.
However, as we couldn't test on rosy for a long time, it could be that this image is now broken somehow...

**Comment by Herrie82** [comment]
@shh632058099 The issue with Rosy should hopefully be solved with https://github.com/webOS-ports/meta-webos-ports/pull/402

**Comment by Tofee** [comment]
When https://github.com/shr-distribution/meta-smartphone/pull/109 will be merged, the new status of the next "testing" build is described in https://www.webos-ports.org/wiki/Device_Status .
For me this issue is fixed, so I'll close it.

**Comment by dimqua** [comment]
@Herrie82 @Tofee could you please provide builds of the latest release?
http://build.webos-ports.org/releases/

**Comment by shh632058099** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
