### ISSUE TITLE
Chromium Webruntime 91 fails to compile for Tenderloin

### ISSUE THREAD

**Issue by Starkka15** [webOS-ports/meta-webos-ports#509]
Good morning gents. Ran into this issue and can't seem to understand what is going on.
I've attached a copy of the error that it hits.
[Error Log.txt](https://github.com/webOS-ports/meta-webos-ports/files/8501602/Error.Log.txt)

**Comment by Tofee** [comment]
I see the following error
`| FileNotFoundError: [Errno 2] No such file or directory: 'python2.7'`

@shr-project I thought the dependency to python2.7 had been removed from webruntime91? Did I misunderstand?

**Comment by Herrie82** [comment]
It should work I guess. Maybe you need to update your layers?

Follow the "update metadata" step in https://webos-ports.org/wiki/Build_for_Tenderloin

I.e. " $ make update-conffiles && make update"

**Comment by Starkka15** [comment]
> It should work I guess. Maybe you need to update your layers?
> 
> Follow the "update metadata" step in https://webos-ports.org/wiki/Build_for_Tenderloin
> 
> I.e. " $ make update-conffiles && make update"

This is a fresh build that I started making yesterday. I did the above and it still gives me the same error when compiling 
Webruntime. Everything else seems to compile fine

**Comment by Herrie82** [comment]
OK I am trying a build here too, could be we need a fix for armv7 somehow

**Comment by Starkka15** [comment]
Is there a way to use the older chromium 87 just to have a build?

**Comment by shr-project** [comment]
@Starkka15 please test with https://github.com/webOS-ports/meta-webos-ports/commit/d7ebafae3e574895d37f73a6f07204b457e2e9d8

**Comment by Starkka15** [comment]
Still running into an issue, How do I apply d7ebafa to my build?

**Comment by Starkka15** [comment]
[new 1.txt](https://github.com/webOS-ports/meta-webos-ports/files/8502637/new.1.txt)
This is what I'm getting, but the source seems to be compiling. I will keep an eye on it

**Comment by Starkka15** [comment]
New Log Her
[log.do_package_write_ipk.txt](https://github.com/webOS-ports/meta-webos-ports/files/8502759/log.do_package_write_ipk.txt)
e

**Comment by shr-project** [comment]
The patch-fuzz issue is probably caused by you incorrectly applying the patch (git cherry-pick d7ebafa in meta-webos-ports would be the easiest). Now I've merged it in the branch together with another fix from @Tofee).

The package-write-ipk "Killed" issue looks like either OOMK was killing it (see dmesg) or you were running out of disk space and bitbake was aborting all pending tasks (there would be warning and error in bitbake output before that).

**Comment by Starkka15** [comment]
What would be causing this issue, I can't compile certain things. I have attached the error log.
[Error when trying to compile.txt](https://github.com/webOS-ports/meta-webos-ports/files/8526416/Error.when.trying.to.compile.txt)

**Comment by Herrie82** [comment]
I am able to boot to a black screen on my latest test image, however, it seems that we need to make some adjustments to our luna-surfacemanager script that assumes that /sys/class/drm exists which is not the case on Tenderloin as per https://github.com/webOS-ports/luna-surfacemanager/blob/webOS-ports/webOS-OSE/base/startup/product.env.in#L91

"adb shell" works at my end so I can create and pull logs. My log for reference: https://pastebin.ubuntu.com/p/fs4XtxNxD8/

**Comment by Starkka15** [comment]
Is there a way to use the older chromium 87 for now?

**Comment by Herrie82** [comment]
We don't have issues here to compile. We recently moved to Qt6 and mainline kernel for Tenderloin, however that would need work still, since it's a very bare and minimal kernel for now. Just console logging and no UI yet.
