### ISSUE TITLE
When compiling web runtime or some of the more extensive issues, I get this

### ISSUE THREAD

**Issue by Starkka15** [webOS-ports/meta-webos-ports#513]
[Error when trying to compile.txt](https://github.com/webOS-ports/meta-webos-ports/files/8526421/Error.when.trying.to.compile.txt)

**Comment by Herrie82** [comment]
Well I tested tenderloin build at my side after updating the layers and all builds OK here now with the latest fixes. I've also tested hammerhead, mako, mido, tissot, qemux86-64, pinephonepro

**Comment by Starkka15** [comment]
> Well I tested tenderloin build at my side after updating the layers and all builds OK here now with the latest fixes. I've also tested hammerhead, mako, mido, tissot, qemux86-64, pinephonepro

What OS are you building on? I've been using WSLv2, but I'd like to try and match your environment.

**Comment by shr-project** [comment]
@Starkka15 see https://github.com/webOS-ports/meta-webos-ports/blob/honister/meta-luneos/conf/distro/include/luneos.inc#L161

Ubuntu-20.04 is best option if you want to use the same OS as we're using. Docker in linux is fine, but I'm not surprised that WSLv2 is broken.
